# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Prepre rpmbuild BUILD dir
      run: mkdir -p ${GITHUB_WORKSPACE}/packages/rpm/rpmbuild/BUILD

    - name: Add build artifact to BUILD dir
      run: cp rpmtest ${GITHUB_WORKSPACE}/packages/rpm/rpmbuild/BUILD

    - name: Create rpm
      run: rpmbuild -bb --define "_topdir ${GITHUB_WORKSPACE}/packages/rpm/rpmbuild" --define "__os_install_post  %{nil}" packages/rpm/rpmtest.spec

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${GITHUB_WORKSPACE}/packages/rpm/rpmbuild/RPMS/x86_64/rpmtest-1-1.x86_64.rpm
